plugins {
    id 'com.android.application'
}

android {
    namespace 'com.kzherdin.blogapp'
    compileSdk 36

    defaultConfig {
        applicationId "com.kzherdin.blogapp"
        minSdk 24
        targetSdk 36
        versionCode 7
        versionName "3.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            minifyEnabled false
            debuggable true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    packaging {
        resources {
            excludes += [
                'META-INF/DEPENDENCIES',
                'META-INF/LICENSE',
                'META-INF/LICENSE.txt',
                'META-INF/NOTICE',
                'META-INF/NOTICE.txt'
            ]
        }
    }
}

dependencies {
    // AndroidX Libraries
    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.recyclerview:recyclerview:1.4.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.2.0'
    implementation 'androidx.activity:activity:1.10.1'

    // Security & Network
    implementation 'org.conscrypt:conscrypt-android:2.5.2'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'

    // Third-party Libraries
    implementation 'de.hdodenhof:circleimageview:3.1.0'
    implementation 'com.android.volley:volley:1.2.1'
    implementation 'com.squareup.picasso:picasso:2.8'
    implementation 'com.facebook.shimmer:shimmer:0.5.0'

    // Testing Libraries
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
